name: kgpg
version: 16.07.70-snap1
summary: Flashcard application.
description: KWordQuiz is a tool that gives you a powerful way to master new vocabularies. It may be a language or any other kind of terminology.

apps:
  kgpg:
    command: qt5-launch usr/bin/kgpg
    plugs: [x11, unity7, home, opengl, network, network-bind, network-manager]

parts:
  kgpg:
    plugin: nil
    stage-packages:
      - kgpg
    filesets:
      binaries:
        - usr/bin
      libraries:
        - usr/lib/*
      headers:
        - usr/include/*
        - usr/lib/*/cmake/*
    stage:
      - etc
      - $libraries
      - $binaries
      - usr/share/*
    snap:
      - etc
      - $libraries
      - $binaries
      - usr/share/*
  environment:
    plugin: copy
    files:
      qt5-launch: bin/qt5-launch
  integration:
    plugin: nil
    stage-packages:
      - breeze-icon-theme
      - plasma-integration
    snap:
      - usr/lib/*
      - usr/share/*
